---
  systems:
    packages:
      - ntp
      - tree
      - vim

  fav: 
    color: yellow
    fruit: banana

  dbconn:
    host: 192.168.61.14
    user: devops
    pass: devops
    db: devopsdemo

  haproxy_backend_servers:
    - name: app1
      address: 192.168.61.12:80
    - name: app2
      address: 192.168.61.13:80
  haproxy_backend_httpchk: ''

  mysql_bind_address: '0.0.0.0'
  mysql_databases:
    - name: devopsdemo
  mysql_users:
    - name: devops
      password: devops
      priv: "devopsdemo.*:ALL"
  mysql_root_password: root
  
